#!/usr/bin/python3

DOMAIN = "lightdm-settings"
PATH = "/usr/share/locale"

import os, gettext
from mintcommon import additionalfiles

os.environ['LANGUAGE'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = """[Desktop Entry]
Encoding=UTF-8
"""

suffix = """Exec=pkexec lightdm-settings
Icon=lightdm-settings
StartupNotify=true
Terminal=false
Type=Application
Categories=GNOME;GTK;Settings;System;XFCE;X-XFCE-SettingsDialog;X-XFCE-SystemSettings;
X-KDE-SubstituteUID=true
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/lightdm-settings.desktop", prefix, _("Login Window"), _("Configure the login window"), suffix)
